#
# This Makefile was automatically generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
pre_processing.f90 \
mod_read_gmsh.f90 \
mod_write_vtk.f90 \
mod_cell_2D.f90 \
mod_objects.f90 \
mod_vector_algebra.f90 \
solver.f90 \
mod_fvm_face_2D.f90 \
euler2d.f90 \
mod_solver_kfvs.f90 \
mod_struct_to_array.f90 \
mod_flux_kfvs.f90 \
mod_point_util.f90 

OBJS_f90d1 = \
pre_processing.o \
mod_read_gmsh.o \
mod_write_vtk.o \
mod_cell_2D.o \
mod_objects.o \
mod_vector_algebra.o \
solver.o \
mod_fvm_face_2D.o \
euler2d.o \
mod_solver_kfvs.o \
mod_struct_to_array.o \
mod_flux_kfvs.o \
mod_point_util.o 

SRC_DIR_f90d1 = 
OBJS_DIR = 
EXE_DIR = 

EXE = euler2D.exe
FC = gfortran
LD = gfortran
IDIR = 
CFLAGS = -ffree-line-length-none -g  
LFLAGS = 
LIBS = 

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1))

all : $(EXE)

$(EXE) : $(OBJS_f90d1)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

clean :
	rm -f *.o *.mod *.exe

# Dependencies of files
pre_processing.o: \
    pre_processing.f90 \
    mod_objects.o
mod_read_gmsh.o: \
    mod_read_gmsh.f90
mod_write_vtk.o: \
    mod_write_vtk.f90 \
    mod_cell_2D.o \
    mod_read_gmsh.o
mod_cell_2D.o: \
    mod_cell_2D.f90 \
    mod_point_util.o \
    mod_read_gmsh.o \
    mod_vector_algebra.o
mod_objects.o: \
    mod_objects.f90 \
    mod_cell_2D.o \
    mod_fvm_face_2D.o \
    mod_read_gmsh.o \
    mod_write_vtk.o
mod_vector_algebra.o: \
    mod_vector_algebra.f90
solver.o: \
    solver.f90 \
    mod_solver_kfvs.o \
    mod_struct_to_array.o
mod_fvm_face_2D.o: \
    mod_fvm_face_2D.f90 \
    mod_cell_2D.o \
    mod_vector_algebra.o
euler2d.o: \
    euler2d.f90
mod_solver_kfvs.o: \
    mod_solver_kfvs.f90 \
    mod_cell_2D.o \
    mod_flux_kfvs.o \
    mod_fvm_face_2D.o \
    mod_struct_to_array.o
mod_struct_to_array.o: \
    mod_struct_to_array.f90 \
    mod_objects.o
mod_flux_kfvs.o: \
    mod_flux_kfvs.f90
mod_point_util.o: \
    mod_point_util.f90 \
    mod_read_gmsh.o

